### ISSUE TITLE
map promise would be nice

### ISSUE THREAD

**Issue by elasticrash** [toutpt/angular-leaflet-light#6]
This is ideal for some of my projects, but I do have a small complain. Except if I am blind, I didn't see any way to call map before being initialized (which is a major drawback for random anync operations). When I say before I mean of course through a  promise. So I had to create a Service that looks like this 

```
...
        var _map = $q.defer();
        var _private = {
            getMap: function () {
                return _map.promise;
            }
        };
        return {
            getMap: function () {
                return _private.getMap();
            },
            setMap: function (map) {
                _map.resolve(map);
            }
}
...
```

the map is set inside the on-map-initialized function

```
model.customise = function (map) {
            mapService.setMap(map);
        };
```

and It is used like this
```
ServiceName.getMap().then(function (map) {
});
```

If I find a bit of spare time I might end up doing a pull request

**Comment by jmfrancois** [comment]
no news from you so I close the issue.
Don't hesitate to contribute.
